In [1]:
import pandas as pd

In [2]:
# Librerias generales
# Pandas
import pandas as pd
pd.set_option('display.max_columns', 25) # Número máximo de columnas a mostrar
pd.set_option('display.max_rows', 50) # Numero máximo de filas a mostar
# Ranom seed
import numpy as np
np.random.seed(3301)

# Seaborn
import seaborn as sns 

# Matplolib
%matplotlib inline
import matplotlib.pyplot as plt

In [8]:
# Ubicacion de la base de datos
db_location = r"C:\Users\Martin\OneDrive\Documentos\Sexto semestre\BI\Lab1\enfermedades.csv"

In [9]:
# Leer los datos
df_tracks = pd.read_csv(db_location)
# Dimensiones de los datos
df_tracks.shape

(67500, 19)

In [10]:
# Ver los datos
display(df_tracks.sample(5)) # Muestra
#display(df_tracks.head(5)) # Primeras Filas
#display(df_tracks.tail(5)) # Ultimas Filas

,Index,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,HeartDisease
49437,49437,28.19,No,No,No,0.0,0.0,No,Female,49-45,White,No,No,Very good,8.0,No,No,No,No
63898,63898,26.57,No,No,No,0.0,5.0,No,Female,29-25,Black,No,Yes,ÚVery goodµ,5.0,No,No,No,No
37386,37386,25.75,No,No,No,0.0,0.0,No,Female,39-35,Hispanic,"No, borderline diabetes",No,Excellent,6.0,No,No,No,NaN
1667,1667,28.48,Yes,No,No,0.0,0.0,No,Male,74-70,White,No,Yes,Very good,200.0,No,No,No,No
3425,3425,28.97,Yes,Yes,No,30.0,0.0,No,Female,or older 80,White,No,No,Very good,4.0,No,Yes,Yes,Yes

In [11]:
# Imprimimos los diferentes tipos de las columnas
df_tracks.dtypes

Index                 int64
BMI                  object
Smoking              object
AlcoholDrinking      object
Stroke               object
PhysicalHealth       object
MentalHealth         object
DiffWalking          object
Sex                  object
AgeCategory          object
Race                 object
Diabetic             object
PhysicalActivity     object
GenHealth            object
SleepTime           float64
Asthma               object
KidneyDisease        object
SkinCancer           object
HeartDisease         object
dtype: object

In [12]:
# Ver el porcentaje de atributos vacios
df_porcentajes = (100*df_tracks.isna().sum()/len(df_tracks)).to_frame()
df_porcentajes.sort_values(0, ascending = False)

                         0
HeartDisease      8.334815
Diabetic          2.472593
Race              2.423704
Smoking           2.402963
GenHealth         2.400000
Sex               2.385185
Stroke            2.379259
BMI               1.965926
SkinCancer        0.000000
KidneyDisease     0.000000
Asthma            0.000000
SleepTime         0.000000
Index             0.000000
PhysicalActivity  0.000000
DiffWalking       0.000000
MentalHealth      0.000000
PhysicalHealth    0.000000
AlcoholDrinking   0.000000
AgeCategory       0.000000

In [16]:
df_tracks_t = df_tracks

# Ahora definimos la función que nos va a permitir construir nuestra clase.
def smoking_label (row):
    if row['Smoking'] == 'No' or  'No' in str(row['Smoking']):
        return 0
    return 1
df_tracks_t['Smoking']=df_tracks_t.apply (lambda row: smoking_label(row), axis=1)

In [18]:
# Ahora definimos la función que nos va a permitir construir nuestra clase.
def transform_label (row,label):
    if row[label] == 'No' or  'No' in str(row[label]):
        return 0
    return 1

In [19]:
df_tracks_t['AlcoholDrinking']=df_tracks_t.apply (lambda row: transform_label(row,'AlcoholDrinking'), axis=1)

In [21]:
df_tracks_t['Stroke']=df_tracks_t.apply (lambda row: transform_label(row,'Stroke'), axis=1) 
df_tracks_t['DiffWalking']=df_tracks_t.apply (lambda row: transform_label(row,'DiffWalking'), axis=1) 
df_tracks_t['Diabetic']=df_tracks_t.apply (lambda row: transform_label(row,'Diabetic'), axis=1)
df_tracks_t['PhysicalActivity']=df_tracks_t.apply (lambda row: transform_label(row,'PhysicalActivity'), axis=1) 
df_tracks_t['Asthma']=df_tracks_t.apply (lambda row: transform_label(row,'Asthma'), axis=1) 
df_tracks_t['KidneyDisease']=df_tracks_t.apply (lambda row: transform_label(row,'KidneyDisease'), axis=1) 
df_tracks_t['SkinCancer']=df_tracks_t.apply (lambda row: transform_label(row,'SkinCancer'), axis=1)

In [22]:
display(df_tracks_t.sample(5)) # Muestra

,Index,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,HeartDisease
3741,3741,31.89,0,0,0,0.0,0.0,0,Female,79-75,White,0,1,Very good,7.0,0,0,0,No
47723,47723,26.63,1,0,0,0.0,3.0,0,Male,39-35,Hispanic,1,0,Very good,7.0,0,0,0,No
47287,47287,23.67,1,0,0,10.0,4.0,0,Male,79-75,vsc,0,1,Fair,7.0,0,0,1,NaN
24830,24830,NaN,0,0,0,0.0,20.0,0,Female,24-18,White,0,1,Excellent,6.0,0,0,0,No
10116,10116,18.72,0,0,0,2.0,-0.0,0,Female,39-35,Hispanic,0,1,Very good,8.0,0,0,0,No

In [26]:
def transform_age (row):
    try:
        edad = int((str(row['AgeCategory']).split('-'))[0])
    except:
        return 70
    return edad

In [27]:
df_tracks_t['AgeCategory']=df_tracks_t.apply (lambda row: transform_age(row), axis=1)

In [29]:
df_tracks_t['HeartDisease']=df_tracks_t.apply (lambda row: transform_label(row,'HeartDisease'), axis=1)

In [30]:
display(df_tracks_t.sample(5)) # Muestra

,Index,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,HeartDisease
44687,44687,22.15,0,0,1,1.0,0.0,0,Male,70,White,0,1,Very good,8.0,0,0,0,0
49375,49375,38.01,0,0,1,0.0,0.0,0,Male,74,White,0,0,Good,8.0,0,0,0,1
20579,20579,22.85,0,0,0,3.0,-0.0,0,Female,70,White,0,1,Good,6.0,0,0,0,0
62964,62964,30.79,1,0,1,0.0,0.0,1,Female,59,White,0,0,Very good,5.0,0,0,0,0
3537,3537,21.13,1,0,0,0.0,2.0,0,Female,74,White,0,1,Excellent,6.0,0,0,0,0